---
- name: Make sure firewalld is installed
  yum:
    name: firewalld
    state: present
  when: couchbase_os.firewalld | default(false) and (ansible_distribution | lower in ['amazon', 'redhat', 'el'])
  tags:
    - couchbase_firewall

- name: Make sure firewalld is installed
  apt:
    name: firewalld
    state: present
  when: couchbase_os.firewalld | default(false) and (ansible_distribution | lower == 'ubuntu')
  tags:
    - couchbase_firewall

- name: Set the default python interpreter to use
  set_fact:
    use_python_interpreter: '/usr/bin/python'

- name: Set the python interpreter to use on Ubuntu
  set_fact:
    use_python_interpreter: '/usr/bin/python3'
  when: couchbase_os.firewalld | default(false) and ansible_distribution | lower == 'ubuntu'

- name: Make sure firewalld is started
  service:
    name: firewalld
    state: started
  when: couchbase_os.firewalld | default(false)
  tags:
    - couchbase_firewall

- name: Add all ports to firewall
  ansible.posix.firewalld:
    port: "{{ item[1] }}/tcp"
    permanent: true
    state: enabled
  vars:
    ansible_python_interpreter: '{{ use_python_interpreter }}'
  when: couchbase_os.firewalld | default(false)
  tags:
    - couchbase_firewall
  loop: "{{ couchbase_ports.items() | list }}"

- name: Make sure firewalld is restarted
  service:
    name: firewalld
    state: restarted
  when: couchbase_os.firewalld | default(false)
  tags:
    - couchbase_firewall
