---
# File: cluster_init.yml
# Example Ansible playbook to initialize a new Couchbase Server cluster

- hosts: cluster_nodes
  sudo: True
  gather_facts: False
  tasks:

  - name: Create cluster grouping
    group_by: key={{ couchbase_server_node_role }}


- hosts: cluster_nodes
  sudo: True
  roles:
    - couchbase.couchbase-server
  tasks:

  - name: Couchbase Server Service
    service: name=couchbase-server state=started

# Initialize the primary cluster node

- hosts: primary
  sudo: True
  gather_facts: False
  vars_files:
    - ../defaults/main.yml
  vars:
    couchbase_server_primary_node: "{{hostvars[groups['primary'][0]]['ansible_fqdn']}}"
  tasks:

  - name: Get major version
    shell: cat /opt/couchbase/VERSION.txt | cut -d '.' -f1
    register: cb_major_version

  - name: Wait for Admin
    wait_for: "port={{ couchbase_server_admin_port }} delay=20"

  - name: Wait for EPMD
    wait_for: "port={{ couchbase_server_admin_port }} delay=20"

  - name: Configure cluster settings
    shell: "{{ couchbase_server_bin_path }}/couchbase-cli cluster-init -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --cluster-init-username={{ couchbase_server_admin }} --cluster-init-password={{ couchbase_server_password }} --cluster-init-port={{couchbase_server_admin_port}} --cluster-init-ramsize={{ couchbase_server_ram }}"

  - name: Initialize primary node
    shell: "{{ couchbase_server_bin_path }}/couchbase-cli node-init -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --cluster-init-username={{ couchbase_server_admin }} --node-init-hostname={{ ansible_fqdn }}"
    when: cb_major_version['stdout'] != "2"


# Initialize additional cluster nodes

- hosts: additional
  sudo: True
  gather_facts: False
  vars_files:
    - ../defaults/main.yml
  tasks:

  - name: Get major version
    shell: cat /opt/couchbase/VERSION.txt | cut -d '.' -f1
    register: cb_major_version

  - name: Wait for Admin
    wait_for: "port={{ couchbase_server_admin_port }} delay=20"

  - name: Wait for EPMD
    wait_for: "port={{ couchbase_server_admin_port }} delay=20"

  - name: Configure cluster settings
    shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli cluster-init -c {{ ansible_fqdn }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --cluster-init-username={{ couchbase_server_admin }} --cluster-init-password={{ couchbase_server_password }} --cluster-init-port={{couchbase_server_admin_port}} --cluster-init-ramsize={{ couchbase_server_ram }}"

  - name: Initialize additional node
    shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli node-init -c {{ ansible_fqdn }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --cluster-init-username={{ couchbase_server_admin }} --node-init-hostname={{ ansible_fqdn }}"
    when: cb_major_version['stdout'] != "2"


# Join additional nodes to the cluster and rebalance

- hosts: primary
  sudo: True
  gather_facts: False
  vars_files:
    - ../defaults/main.yml
  vars:
    couchbase_server_primary_node: "{{hostvars[groups['primary'][0]]['ansible_fqdn']}}"
  tasks:

  - name: Create cluster grouping
    group_by: key={{ couchbase_server_node_role }}

  - name: Get major version
    shell: cat /opt/couchbase/VERSION.txt | cut -d '.' -f1
    register: cb_major_version

  - name: Join additional cluster nodes
    shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli server-add -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --server-add={{hostvars[[item][0]]['inventory_hostname']}}:{{ couchbase_server_admin_port }} --server-add-username={{ couchbase_server_admin }} --server-add-password={{ couchbase_server_password }}"
    with_items: groups['additional']

  - name: Rebalance cluster
    shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli rebalance -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }}"
