---
# Docs: https://docs.couchbase.com/server/current/cli/cbcli/couchbase-cli-cluster-init.html
- name: Initialize the Cluster
  no_log: true
  shell:
    cmd: |
      if /opt/couchbase/bin/couchbase-cli setting-cluster \
        --cluster {{ inventory_hostname }} \
        --username {{ couchbase_security.admin_user | default('Administrator') }} \
        --password '{{ couchbase_security.admin_password | default('password') }}' | \
        grep -q 'ERROR: Cluster is not initialized'; then
        /opt/couchbase/bin/couchbase-cli cluster-init \
          --cluster {{ inventory_hostname }} \
          --cluster-username {{ couchbase_security.admin_user | default('Administrator') }} \
          --cluster-password '{{ couchbase_security.admin_password | default('password') }}' \
          --cluster-port {{ couchbase_cluster.port | default(8091) }} \
          --cluster-ramsize {{ couchbase_memory_quotas.data | default(1024) }} \
          --cluster-fts-ramsize {{ couchbase_memory_quotas.fts | default(256) }} \
          --cluster-index-ramsize {{ couchbase_memory_quotas.index | default(256) }} \
          {% if (item.services is defined and 'eventing' in item.services) or 'eventing' in couchbase_cluster.default_services %} --cluster-eventing-ramsize {{ couchbase_memory_quotas.eventing | default(256) }}{% endif %} \
          {% if (item.services is defined and 'analytics' in item.services) or 'analytics' in couchbase_cluster.default_services %} --cluster-analytics-ramsize {{ couchbase_memory_quotas.analytics | default(1024) }}{% endif %} \
          --cluster-name '{{ couchbase_cluster.name | default('My Cluster') }}' \
          --index-storage-setting {{ couchbase_cluster.index_storage | default('default') }} \
          --services '{{ item.services is defined |
            ternary(item.services, couchbase_cluster.default_services |
            default(['data','index','query'])) |
            join(',') }}'
      else
        echo "Already initialized"
      fi
  loop: "{{ couchbase_nodes }}"
  when: couchbase_master is defined and couchbase_master == inventory_hostname and couchbase_master == item.hostname
