---
- name: Make sure required dirs exist
  file:
    path: "{{ item.value }}"
    state: directory
    owner: couchbase
    group: couchbase
  loop: "{{ couchbase_paths | dict2items }}"

# Docs: https://docs.couchbase.com/server/current/cli/cbcli/couchbase-cli-node-init.html
- name: Initialize the Node
  shell:
    cmd: |
      if /opt/couchbase/bin/couchbase-cli host-list \
        --cluster {{ inventory_hostname }} \
        --username {{ couchbase_security.admin_user | default('Administrator') }} \
        --password '{{ couchbase_security.admin_password | default('password') }}' | \
        grep -q '{{ item.hostname }}'; then
          echo "The node already exists in the cluster"
      else
        /opt/couchbase/bin/couchbase-cli node-init \
          --cluster {{ item.hostname }} \
          --username {{ couchbase_security.admin_user | default('Administrator') }} \
          --password '{{ couchbase_security.admin_password | default('password') }}' \
          --node-init-hostname '{{ item.hostname }}' \
          --node-init-data-path '{{ couchbase_paths.data }}' \
          --node-init-index-path '{{ couchbase_paths.index }}' \
          {% if couchbase_server_version is version_compare('6.5', '>=') %}--node-init-eventing-path '{{ couchbase_paths.eventing }}'{% endif %} \
          --node-init-analytics-path '{{ couchbase_paths.analytics }}'
      fi
  with_items: "{{ couchbase_nodes }}"
  when: couchbase_master is defined
